#####################################
# Example oneill configuration file #
#####################################

# This file shows all possible settings keys with explanations on the use of
# each one. The default value for each key is shown.

# see README.md for explanation of appropriate values for `definitions_uri`
definitions_uri: "file:///etc/oneill/definitions"

# docker_api_endpoint defines the url oneill will use to connect to the docker
# API. By default this uses a unix socket at `/var/run/docker.sock` but it
# could also be a remote docker daemon communicating via HTTP.
docker_api_endpoint: "unix:///var/run/docker.sock"

# log_format controls the format of the output produced by oneill. The following
# values are permitted: text (default), json
log_format: text

# log_level controls the amount of output produced by oneill. The following
# values are permitted: debug, info, warning, error, fatal, panic
log_level: info

# persistence_directory controls the directory under which oneill will store
# any data from persistent containers.
persistence_directory: "/var/lib/oneill/data"

# registry_credentials is a map in which you can specify login details for any
# private registry you wish to use with oneill (you can ignore this if your
# private registry does not require login). The keys should be the name/url
# (without scheme) of the registry, the values should be another map
# containing both the username and password that should be used for each
# registry.
#
# Note: There are no default values provided for registry credentials, but an
# example is shown below.
registry_credentials:
    registry.example.com:
        username: user@example.com
        password: examplepassword
    another-registry.example.com:
        username: anotheruser@example.com
        password: anotherexamplepassword
